package net.netconomy.eld.interfaces.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Начисление (обновление) бонусов
 *
 * This class was generated by Apache CXF 2.7.11
 * 2015-08-09T00:00:56.844+04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "url:eldorado.ru:HBRS.INT_PI01_73_10.Bonuses", name = "UpdateBonusOrder_SI_Sync_In")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateBonusOrderSISyncIn {

    @WebResult(name = "UpdateBonusOrderResponse", targetNamespace = "url:eldorado.ru:HBRS.INT_PI01_73_10.Bonuses", partName = "parameters")
    @WebMethod(operationName = "UpdateBonusOrder_SI_Sync_In")
    public UpdateBonusOrderResponse updateBonusOrderSISyncIn(
        @WebParam(partName = "parameters", name = "UpdateBonusOrder", targetNamespace = "url:eldorado.ru:HBRS.INT_PI01_73_10.Bonuses")
        UpdateBonusOrder parameters
    );
}
